name: mybudget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_login: ^5.0.0
  foundation: ^0.0.5
  get_it: ^8.0.3
  http: ^1.4.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  introduction_screen: ^3.1.17
  persistent_bottom_nav_bar_v2: ^5.2.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
